# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0001_initial'),
        ('myapp', '0002_category_f_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='u',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.User'),
        ),
    ]
