# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_article_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
