# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181203_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='a_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='icon',
            field=models.ImageField(null=True, upload_to='article'),
        ),
    ]
